// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: proto/image_processing.proto

package ImageProcessing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageProcessing_ProcessImage_FullMethodName = "/ImageProcessing/ProcessImage"
)

// ImageProcessingClient is the client API for ImageProcessing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageProcessingClient interface {
	ProcessImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error)
}

type imageProcessingClient struct {
	cc grpc.ClientConnInterface
}

func NewImageProcessingClient(cc grpc.ClientConnInterface) ImageProcessingClient {
	return &imageProcessingClient{cc}
}

func (c *imageProcessingClient) ProcessImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageResponse)
	err := c.cc.Invoke(ctx, ImageProcessing_ProcessImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageProcessingServer is the server API for ImageProcessing service.
// All implementations must embed UnimplementedImageProcessingServer
// for forward compatibility.
type ImageProcessingServer interface {
	ProcessImage(context.Context, *ImageRequest) (*ImageResponse, error)
	mustEmbedUnimplementedImageProcessingServer()
}

// UnimplementedImageProcessingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageProcessingServer struct{}

func (UnimplementedImageProcessingServer) ProcessImage(context.Context, *ImageRequest) (*ImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessImage not implemented")
}
func (UnimplementedImageProcessingServer) mustEmbedUnimplementedImageProcessingServer() {}
func (UnimplementedImageProcessingServer) testEmbeddedByValue()                         {}

// UnsafeImageProcessingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageProcessingServer will
// result in compilation errors.
type UnsafeImageProcessingServer interface {
	mustEmbedUnimplementedImageProcessingServer()
}

func RegisterImageProcessingServer(s grpc.ServiceRegistrar, srv ImageProcessingServer) {
	// If the following call pancis, it indicates UnimplementedImageProcessingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageProcessing_ServiceDesc, srv)
}

func _ImageProcessing_ProcessImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageProcessingServer).ProcessImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageProcessing_ProcessImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageProcessingServer).ProcessImage(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageProcessing_ServiceDesc is the grpc.ServiceDesc for ImageProcessing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageProcessing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ImageProcessing",
	HandlerType: (*ImageProcessingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessImage",
			Handler:    _ImageProcessing_ProcessImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/image_processing.proto",
}
